# Generated by Django 4.1.5 on 2023-03-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='subdivision_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL, verbose_name='Инженер подразделения'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='subdivision_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='book_instructions.positions', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='services',
            name='services_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Начальник службы'),
        ),
        migrations.AddField(
            model_name='services',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_subdivision', to='book_instructions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='region',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Начальник участка'),
        ),
        migrations.AddField(
            model_name='prescriptiontypes',
            name='types',
            field=models.ManyToManyField(related_name='order_types', to='book_instructions.ordertypes', verbose_name='Доступные типы распоряжений'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто составил предписание'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_instructions.region', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_instructions.services', verbose_name='К какой службе'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_instructions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='type_prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_instructions.prescriptiontypes', verbose_name='Тип предписания'),
        ),
        migrations.AddField(
            model_name='positions',
            name='types',
            field=models.ManyToManyField(related_name='prescription_types', to='book_instructions.prescriptiontypes', verbose_name='Типы предписаний'),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_instructions.ordertypes', verbose_name='Тип распоряжения'),
        ),
        migrations.AddField(
            model_name='orders',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_prescription', to='book_instructions.prescription', verbose_name='Предписание'),
        ),
        migrations.AddField(
            model_name='orders',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное  лицо'),
        ),
        migrations.AddField(
            model_name='orderexecutions',
            name='order_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_execution', to='book_instructions.orders', verbose_name='Распоряжение'),
        ),
        migrations.AddField(
            model_name='dispatchers',
            name='services_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='dispatchers',
            name='subdivision',
            field=models.ManyToManyField(to='book_instructions.subdivision', verbose_name='Подразделение инженера'),
        ),
    ]
