# Generated by Django 4.1.5 on 2023-03-17 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_instructions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_instructions.services', verbose_name='К какой службе'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_instructions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='Dispatchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=250, verbose_name='Название диспетчера')),
                ('services_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_user', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер')),
                ('subdivision', models.ManyToManyField(to='book_instructions.subdivision', verbose_name='Подразделение инженера')),
            ],
            options={
                'verbose_name': 'Диспетчер',
                'verbose_name_plural': 'Диспетчера',
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispatcher_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_prescription', to='book_instructions.dispatchers', verbose_name='Какому диспетчеру'),
        ),
    ]
