# Generated by Django 4.1.5 on 2023-03-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_instructions', '0003_alter_prescription_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchers',
            name='services_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_user', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер'),
        ),
    ]
