from django.urls import path

from book_instructions.views import (HomePage, PrescriptionList,
                                     CreatePrescription, EditPrescription,
                                     DelPrescription, GetPrescription,
                                     CreateOrders, GetServices,
                                     orders_acquainted, CreateOrderExecutions,
                                     GetOrderExecutions,
                                     executions_finalize, EditOrderExecutions,
                                     executions_ready, GetServicesChief,
                                     DispatcherServices,
                                     EditDispatcherPrescription,
                                     GetDispatcherPrescription,
                                     orders_acquainted_dispatcher, )

app_name = 'book_instructions'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('prescription/', PrescriptionList.as_view(),
         name='all_prescription'),
    path('prescription/create/<int:pk>/<int:service_id>/',
         CreatePrescription.as_view(),
         name='create_prescription'),
    path('prescription/edit/<int:pk>/<int:service_id>/',
         EditPrescription.as_view(),
         name='edit_prescription'),
    path('prescription/<pk>/delete/<int:service_id>/',
         DelPrescription.as_view(),
         name='del_prescription'),
    path('prescription/view/<int:pk>/', GetPrescription.as_view(),
         name='view_prescription'),
    path(
        'orders/create/<int:pk>/<int:type_id>/<int:subdivision_id>/<int:orders_id>/',
        CreateOrders.as_view(),
        name='create_orders'),
    path('services/<int:pk>/', GetServices.as_view(),
         name='view_services'),
    path('services/<int:pk>/<str:search>', GetServices.as_view(),
         name='view_services_search'),
    path('services_chief/<int:pk>/', GetServicesChief.as_view(),
         name='view_services_chief'),
    path('services_chief/<int:pk>/<str:search>', GetServicesChief.as_view(),
         name='view_services_chief_search'),
    path('order_status/<int:orders_id>/<int:presc_id>/', orders_acquainted,
         name='order_status'),
    path('order_executions/<int:order_id>/<int:presc_id>/',
         CreateOrderExecutions.as_view(),
         name='order_executions'),
    path('edit_executions/<int:pk>/<int:presc_id>/',
         EditOrderExecutions.as_view(),
         name='edit_executions'),
    path('view_order_executions/<int:pk>/<int:order_id>/',
         GetOrderExecutions.as_view(),
         name='view_order_executions'),
    path('order_finalize/<int:executions_id>/<int:order_id>/',
         executions_finalize,
         name='executions_finalize'),
    path('order_ready/<int:executions_id>/<int:order_id>/', executions_ready,
         name='executions_ready'),

    path('dispatchers/',
         DispatcherServices.as_view(),
         name='view_dispatchers'),
    path('dispatchers/edit/<int:pk>/',
         EditDispatcherPrescription.as_view(),
         name='edit_dispatchers'),
    path('dispatchers/view/<int:pk>/', GetDispatcherPrescription.as_view(),
         name='view_prescription_dispatchers'),
    path('order_dispatchers_status/<int:orders_id>/<int:presc_id>/',
         orders_acquainted_dispatcher,
         name='order_status_dispatcher'),

]
